//Made by zakarum5835

ServerEvents.recipes(event => {

event.remove({ id: 'legendarysurvivaloverhaul:canteen' })
event.remove({ id: 'legendarysurvivaloverhaul:large_canteen' })
event.remove({ id: 'legendarysurvivaloverhaul:bandage' })
event.remove({ id: 'legendarysurvivaloverhaul:medkit' })
event.remove({ id: 'minecraft:diamond_helmet' })
event.remove({ id: 'minecraft:diamond_chestplate' })
event.remove({ id: 'minecraft:diamond_leggings' })
event.remove({ id: 'minecraft:diamond_boots' })
event.remove({ id: 'minecraft:diamond_shovel' })
event.remove({ id: 'minecraft:diamond_hoe' })
event.remove({ id: 'minecraft:diamond_pickaxe' })
event.remove({ id: 'minecraft:diamond_axe' })
event.remove({ id: 'minecraft:diamond_sword' })
event.remove({ id: 'minecraft:netherite_helmet_smithing' })
event.remove({ id: 'minecraft:netherite_chestplate_smithing' })
event.remove({ id: 'minecraft:netherite_leggings_smithing' })
event.remove({ id: 'minecraft:netherite_boots_smithing' })
event.remove({ id: 'blazegear:nethersteel_helmet' })
event.remove({ id: 'blazegear:nethersteel_chestplate' })
event.remove({ id: 'blazegear:nethersteel_leggings' })
event.remove({ id: 'blazegear:nethersteel_boots' })
event.remove({ id: 'blazegear:nethersteel_sword' })
event.remove({ id: 'blazegear:nethersteel_pickaxe' })
event.remove({ id: 'blazegear:nethersteel_axe' })
event.remove({ id: 'blazegear:nethersteel_shovel' })
event.remove({ id: 'blazegear:nethersteel_hoe' })
event.remove({ id: 'minecraft:music_disc_5' })
event.remove({ id: 'goety:infernal_tome' })
event.remove({ id: 'enigmaticlegacy:twisted_heart' })
event.remove({ id: 'enigmaticaddons:pure_heart' })
event.remove({ id: 'betterend:eternal_crystal' })
event.remove({ id: 'celestisynth:celestial_core' })
event.remove({ id: 'voidscape:voidic/voidic_crystal_helmet' })
event.remove({ id: 'voidscape:voidic/voidic_crystal_chest' })
event.remove({ id: 'voidscape:voidic/voidic_crystal_legs' })
event.remove({ id: 'voidscape:voidic/voidic_crystal_boots' })
event.remove({ id: 'voidscape:voidic/voidic_crystal_chest_elytra' })
event.remove({ id: 'voidscape:voidic/voidic_crystal_sword' })
event.remove({ id: 'voidscape:voidic/voidic_crystal_axe' })
event.remove({ id: 'voidscape:voidic/voidic_crystal_pickaxe' })
event.remove({ id: 'celestisynth:supernal_netherite_ingot_smithing_from_core' })
event.remove({ id: 'celestisynth:supernal_netherite_ingot_smithing' })
event.remove({ id: 'goety:cursed_ingot_craft_dnl' })
event.remove({ id: 'goety:cursed_ingot_craft' })
event.remove({ id: 'goety:totem_of_souls' })
event.remove({ id: 'legendarysurvivaloverhaul:healing_herbs' })
event.remove({ id: 'ancient_elements:galactrium_upgrade_template' })
event.remove({ id: 'lethality:gamblers_blade' })
event.remove({ id: 'lethality:nightmare_sword' })
event.remove({ id: 'lethality:nightfall' })
event.remove({ id: 'brutality:providence' })

})